name: ci-netverify

on:
  push:

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: golang:1.12-alpine
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: false
          vuln-type: 'os,library'
          exit-code: 0

      - run: cat trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
